### ISSUE TITLE
PTR - AddOn not working at all

### ISSUE THREAD

**Issue by Plusader** [tullamods/Bagnon#1018]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.2.16-8.2.5
 - Server patch: 8.3.0.32593

 **Have you read the changelog? (please don't waste our time)**
 Yes.

**Describe the bug**
Opening the bag manually or while speaking to a vendor which opens them automatically (usually) only returns error message

**To Reproduce**
Steps to reproduce the behaviour:
1. Click Hotkey to open Bags
1.1. or speak to vendor(do something that opens bags automatically)
2. See error

**Expected behaviour**
Open bags in different situations (manually, at vendor,...)

**Error Logs**
Message: ...e\AddOns\Bagnon\common\Wildpants\components\item.lua:93: attempt to perform arithmetic on global 'MAX_CONTAINER_ITEMS' (a nil value)
Time: Sun Nov 24 11:49:03 2019
Count: 5
Stack: ...e\AddOns\Bagnon\common\Wildpants\components\item.lua:93: attempt to perform arithmetic on global 'MAX_CONTAINER_ITEMS' (a nil value)
[string "@Interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:93: in function `GetBlizzard'
[string "@Interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:37: in function `Create'
[string "@Interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:21: in function `New'
[string "@Interface\AddOns\Bagnon\common\Wildpants\components\itemFrame.lua"]:123: in function <...Ons\Bagnon\common\Wildpants\components\itemFrame.lua:112>

Locals: self = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:203
 Free = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:108
 IconOverlay = <unnamed> {
 }
 itemContextChangedCallback = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:207
 Bind = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:53
 IconBorder = <unnamed> {
 }
 OnDragStart = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:139
 icon = TopIconTexture {
 }
 OnShow = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:119
 IsCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:93
 Create = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:35
 GetFrame = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:98
 GetFrameID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:69
 GetEmptyItemIcon = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:443
 IsQuestItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:398
 GetBaseProfile = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:79
 RegisterMessage = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 PostOnShow = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:226
 RegisterFrameSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:57
 GetBlizzard = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:88
 UpdateSearch = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:334
 Restore = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:104
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:27
 UpdateItemContextOverlay = <function> defined @Interface\FrameXML\ItemButtonTemplate.lua:259
 GetProfile = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:74
 Count = TopCount {
 }
 OnPreClick = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:143
 searchOverlay = TopSearchOverlay {
 }
 Construct = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:84
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:31
 OnModifiedClick = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:196
 UnregisterAllEvents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UpdateSlotColor = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:301
 OnItemFlashed = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\components\item.lua:350
 Cr

**Comment by Jaliborc** [comment]
Gotcha. Haven’t gone to the PTR yet.  From: PlusaderSent: Sunday, November 24, 2019 11:53 AMTo: tullamods/BagnonCc: SubscribedSubject: [tullamods/Bagnon] PTR error message (#1018) Running Software (issues missing this information will be deleted):Addon version: 8.2.16-8.2.5Server patch: 8.3.0.32593Have you read the changelog? (please don't waste our time)Yes.Describe the bugOpening the bag manually or while speaking to a vendor which opens them automatically (usually) only returns error messageTo ReproduceSteps to reproduce the behaviour:Click Hotkey to open Bags1.1. or speak to vendor(do something that opens bags automatically)See errorExpected behaviourOpen bags in different situations (manually, at vendor,...)Error LogsMessage: ...e\AddOns\Bagnon\common\Wildpants\components\item.lua:93: attempt to perform arithmetic on global 'MAX_CONTAINER_ITEMS' (a nil value)Time: Sun Nov 24 11:49:03 2019Count: 5Stack: ...e\AddOns\Bagnon\common\Wildpants\components\item.lua:93: attempt to perform arithmetic on global 'MAX_CONTAINER_ITEMS' (a nil value)[string "@interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:93: in function GetBlizzard' [string "@Interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:37: in function Create'[string "@interface\AddOns\Bagnon\common\Wildpants\components\item.lua"]:21: in function `New'[string "@interface\AddOns\Bagnon\common\Wildpants\components\itemFrame.lua"]:123: in function <...Ons\Bagnon\common\Wildpants\components\itemFrame.lua:112>Locals: self = {0 = OnEnter = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:203Free = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:108IconOverlay = {}itemContextChangedCallback = defined @interface\FrameXML\ItemButtonTemplate.lua:207Bind = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:53IconBorder = {}OnDragStart = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:139icon = TopIconTexture {}OnShow = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:119IsCached = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:93Create = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:35GetFrame = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:98GetFrameID = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:69GetEmptyItemIcon = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:443IsQuestItem = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:398GetBaseProfile = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:79RegisterMessage = defined @interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90UnregisterMessage = defined @interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153PostOnShow = defined @interface\FrameXML\ItemButtonTemplate.lua:226RegisterFrameSignal = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:57GetBlizzard = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:88UpdateSearch = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:334Restore = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:104UnregisterSignal = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:27UpdateItemContextOverlay = defined @interface\FrameXML\ItemButtonTemplate.lua:259GetProfile = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:74Count = TopCount {}OnPreClick = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:143searchOverlay = TopSearchOverlay {}Construct = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:84SendSignal = defined @interface\AddOns\Bagnon\common\Wildpants\core\classes.lua:31OnModifiedClick = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:196UnregisterAllEvents = defined @interface\AddOns\Bagnon\common\Wildpants\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174UpdateSlotColor = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:301OnItemFlashed = defined @interface\AddOns\Bagnon\common\Wildpants\components\item.lua:350Cr—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jaliborc** [comment]
They turned many constants into locals... oh boy
