### ISSUE TITLE
Basic wow bags being displayed instead of Bagnon

### ISSUE THREAD

**Issue by Ha11eck** [tullamods/Bagnon#1104]
Date: 2019-12-24 01:53:37
ID: 5
Error occured in: Global
Count: 1
Message: ...ace\AddOns\Bagnon\common\Wildpants\config\frames.lua line 13:
   attempt to index field 'profile' (a nil value)
Debug:
   [C]: ?
   ...ace\AddOns\Bagnon\common\Wildpants\config\frames.lua:13: Populate()
   ...ace\AddOns\Bagnon\common\Wildpants\config\shared.lua:19: method()
   ...n\Wildpants\libs\Sushi-3.1\classes\core\Callable.lua:52: FireCalls()
   ...on\Wildpants\libs\Sushi-3.1\classes\groups\Group.lua:70:
      ...on\Wildpants\libs\Sushi-3.1\classes\groups\Group.lua:67
   [C]: Show()
   ..\FrameXML\InterfaceOptionsFrame.lua:28: InterfaceOptionsList_DisplayPanel()
   ..\FrameXML\InterfaceOptionsFrame.lua:46: InterfaceOptionsListButton_OnClick()
   [string "*:OnClick"]:2:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AddOnSkins, v4.39
  Altoholic, vr191
  AtlasLoot, vv8.10.00
  AtlasLootBattleforAzeroth, vv8.10.00
  AtlasLootBurningCrusade, vv8.10.00
  AtlasLootCataclysm, vv8.10.00
  AtlasLootClassic, vv8.10.00
  AtlasLootLegion, vv8.10.00
  AtlasLootMistsofPandaria, vv8.10.00
  AtlasLootWarlordsofDraenor, vv8.10.00
  AtlasLootWrathoftheLichKing, vv8.10.00
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AutoRepair, v
  AzeritePowerWeights, v8.2.16
  BagBrother, v
  Bagnon, v8.2.25
  BagnonConfig, v
  BagnonItemInfo, v1.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Clique, vv80200-1.2.2
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v11.27
  ElvUICliqueDatatext, v1.11
  ElvUICustomTweaks, v1.49
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  Incognito, v1.4.1
  Informant, v8.2.6508 (SwimmingSeadragon)
  MogIt, v3.9.0
  MogItArtifact, v3.9.0
  MogItHighlighter, vv1.3.2
  MogItMail, v3.9.0
  MogItOneHanded, v3.9.0
  MogItOther, v3.9.0
  MogItRanged, v3.9.0
  MogItTwoHanded, v3.9.0
  NameplateSCT, v1.17
  ParagonReputation, v1.25
  RaiderIO, v8.1.0 (v201912240600)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  SlideBar, v8.2.6509 (SwimmingSeadragon)
  Stubby, v8.2.6510 (SwimmingSeadragon)
  SYH, v
  TomCats, v1.3.6
  TomCatsMechagon, v1.3.10
  TomCatsNazjatar, v1.3.10
  WeakAuras, v2.15.5
  WIM, v3.8.4
  WIMElvUISkin, v80000.01-Release
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=9f2)

**Comment by Ha11eck** [comment]
Nothing is being displayed in the options/config windows either

**Comment by xhaven** [comment]
Yep I have this same issue now since two days ago, I am also updated bagnon to the lastest patch so far issue still persists.

Message: Interface\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua:20: attempt to index local 'ItemSlot' (a nil value)
Time: Tue Dec 24 08:42:07 2019
Count: 1
Stack: Interface\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua:20: attempt to index local 'ItemSlot' (a nil value)
Interface\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua:20: in main chunk

Locals: Addon = <table> {
 IsKeyring = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:375
 IsRetail = true
 GetOwnerID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:270
 Frames = <table> {
 }
 InBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:352
 ItemGroup = <table> {
 }
 RestoreItemData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:304
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:379
 RegisterMessage = <function> defined @Interface\AddOns\Armory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Armory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:291
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:275
 Slash = "bgn"
 OnEnable = <function> defined @Interface\AddOns\Bagnon_ItemInfo\main.lua:510
 Name = "Bagnon"
 IterateOwners = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:114
 InGuild = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:360
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 RestoreLinkData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:328
 Item = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 SortButton = <table> {
 }
 InventoryFrame = <table> {
 }
 ItemInfo = <table> {
 }
 Title = <table> {
 }
 BagGroup = <table> {
 }
 SearchToggle = <table> {
 }
 Events = <table> {
 }
 SearchFrame = <table> {
 }
 TooltipCounts = <table> {
 }
 BrokerDisplay = <table> {
 }
 LDB = <table> {
 }
 Tag = "BAGNON_"
 PickupItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:250
 IsBackpackBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:371
 IsOwnerCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:287
 AutoDisplay = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Armory\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Sorting = <table> {
 }
 BankFrame = <table> {
 }
 Parented = <table> {
 }
 GetItemID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:229
 IsReagents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:387
 IsBankBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:383
 Owners = <table> {
 }
 ShowOptions = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:157
 GetBagInfo = <function> defined @Interface\AddOns\Bag
