### ISSUE TITLE
Hi  Still have Bagon issues.  Thank you:

### ISSUE THREAD

**Issue by zamis21** [tullamods/Bagnon#1107]
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Mark if read.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message (labelled 1/Many) that appeared.

**Additional context**

**Comment by zamis21** [comment]
opps here:  
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon_ItemInfo\main.lua line 511:
   Usage: hooksecurefunc([table,] "function", hookfunc)
Debug:
   (tail call): ?
   [C]: hooksecurefunc()
   Bagnon_ItemInfo\main.lua:511: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: ?
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:448: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:567: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1240:
      ..\FrameXML\UIParent.lua:1138
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AlreadyKnown, v1.22
  Altoholic, vr191
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  AzeritePowerWeights, v8.2.16
  Bagnon, v8.2.25
  BagnonBoE, v1.0
  BagnonItemInfo, v1.0
  BattlePetBreedID, vr203
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CrematoriusChatSounds, v7.xx
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  HandyNotes, vv1.5.9
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesWarfrontRares, v0.5.0
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  MaxDps, v8.2.8
  PetTracker, v8.2.2
  PetTrackerBreeds, v8.2.2
  PetTrackerSwitcher, v8.2.2
  PetTrackerUpgrades, v8.2.2
  Postal, vv3.6.0
  Recount, vv8.2.5d
  Rematch, v4.9.13
  sellgrey, v8.2.5
  Stubby, v8.2.6510 (SwimmingSeadragon)
  Titan, v5.18.4.80205
  TitanBag, v5.18.4.80205
  TitanClock, v5.18.4.80205
  TitanGold, v5.18.4.80205
  TitanLocation, v5.18.4.80205
  TitanLootType, v5.18.4.80205
  TitanPerformance, v5.18.4.80205
  TitanRepair, v5.18.4.80205
  TitanVolume, v5.18.4.80205
  TitanXP, v5.18.4.80205
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=811)

**Comment by Gingy92** [comment]
Running Software (issues missing this information will be deleted):

Addon version: Bagnon-8.2.25-8.2.5
Server patch: 8.2.5.32750
Have you read the changelog? (please don't waste our time)
**Changelog read** 

Describe the bug
Bagnon has not loaded for several days or sometimes not being recognized by the game as installed or recognized by the game when going to 'Addons' in the menu.

To Reproduce
Steps to reproduce the behaviour:
1.) Login to World of Warcraft [retail]
2.) See error
Expected behaviour
I expected the be able to open my bags with bagnon, but it is not, default bags are just showing. I expected the addon to be recognized and to load when i opened the game.

Error Log
Date: 2019-12-24 11:50:12
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon_Scrap\Bagnon_Scrap.lua line 20:
   attempt to index local 'ItemSlot' (a nil value)
Debug:
   Bagnon_Scrap\Bagnon_Scrap.lua:20: in main chunk
Locals:
Addon = <table> {
 IsKeyring = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:375
 IsRetail = true
 GetOwnerID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:270
 Frames = <table> {
 }
 BindOnEquip = <table> {
 }
 InBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:352
 ItemGroup = <table> {
 }
 RestoreItemData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:304
 Frame = <table> {
 }
 OptionsToggle = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:379
 RegisterMessage = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:153
 IsBagCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:291
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:275
 Slash = "bgn"
 OnEnable = <function> defined @Interface\AddOns\Bagnon_ItemLevel\main.lua:209
 Name = "Bagnon"
 IterateOwners = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:114
 InGuild = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:360
 SendSignal = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 RestoreLinkData = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:328
 GarbageColoring = <table> {
 }
 Item = <table> {
 }
 OwnerSelector = <table> {
 }
 Commands = <table> {
 }
 SortButton = <table> {
 }
 InventoryFrame = <table> {
 }
 ItemLevel = <table> {
 }
 Title = <table> {
 }
 BagGroup = <table> {
 }
 SearchToggle = <table> {
 }
 Events = <table> {
 }
 SearchFrame = <table> {
 }
 TooltipCounts = <table> {
 }
 BrokerDisplay = <table> {
 }
 LDB = <table> {
 }
 Tag = "BAGNON_"
 PickupItem = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:250
 IsBackpackBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:371
 IsOwnerCached = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:287
 AutoDisplay = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Auc-Advanced\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:174
 Sorting = <table> {
 }
 BankFrame = <table> {
 }
 Parented = <table> {
 }
 GetItemID = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:229
 IsReagents = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:387
 IsBankBag = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:383
 Owners = <table> {
 }
 ShowOptions = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\Wildpants.lua:157
 GetBagInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:145
 DropButton = <table> {
 }
 BagToggle = <table> {
 }
 Rules = <table> {
 }
 GetOwnerInfo = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:74
 MoneyFrame = <table> {
 }
 Tipped = <table> {
 }
 RegisterSignal = <function> defined @Interface\AddOns\Bagn
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.25
  BagnonBoE, v1.0
  BagnonGarbage, v1.0
  BagnonItemLevel, v1.0
  BagnonScrap, v8.2.0
  Scrap, v8.2.0
  Stubby, v8.2.6510 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=27f)

Error Log #2

Date: 2019-12-24 11:56:33
ID: 3
Error occured in: Global
Count: 1
Message: ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua line 70:
   attempt to index field 'sets' (a nil value)
Debug:
   (tail call): ?
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:70: RegisterDisplayEvents()
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:28: RegisterGameEvents()
   ...Ons\Bagnon\common\Wildpants\features\autoDisplay.lua:13: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:448: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:491: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:1242:
      ..\FrameXML\UIParent.lua:1138
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.25
  BagnonBoE, v1.0
  BagnonGarbage, v1.0
  BagnonItemLevel, v1.0
  BagnonScrap, v8.2.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Capping, vv8.2.11
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyScrap, v24
  ElvUI, v11.27
  GTFO, v4.51
  HandyNotes, vv1.5.9
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HealBot, v8.2.5.8
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  HealBotTips, v8.2.5.8
  MikScrollingBattleText, v5.7.150
  MythicPlusTimer, v3.4
  NPCScan, v8.0.1.13
  Pawn, v2.3.13
  QuickQuest, v80200.40-Release
  RaiderIO, v8.1.0 (v201912240637)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  SavedInstances, v8.2.7
  Scrap, v8.2.0
  Simulationcraft, v1.12.3
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomCats, v1.3.6
  TomCatsMechagon, v1.3.10
  TomCatsNazjatar, v1.3.10
  TomTom, vv80205-1.0.9
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WorldQuestsList, v91
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=67b)

Error Log #3 

Date: 2019-12-24 11:56:34
ID: 4
Error occured in: Global
Count: 1
Message: ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua line 179:
   attempt to index field 'sets' (a nil value)
Debug:
   (tail call): ?
   ...s\Bagnon\common\Wildpants\features\tooltipCounts.lua:179: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: LoadAddOn()
   [string "		local loadType = Stubby.GetConfig("Inform..."]:3: in main chunk
   [C]: RunScript()
   Stubby\Stubby.lua:914:
      Stubby\Stubby.lua:907
   Stubby\Stubby.lua:927: f()
   Stubby\Stubby.lua:738: EventWatcher()
   Stubby\Stubby.lua:958: Events()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.25
  BagnonBoE, v1.0
  BagnonGarbage, v1.0
  BagnonItemLevel, v1.0
  BagnonScrap, v8.2.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Capping, vv8.2.11
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyScrap, v24
  ElvUI, v11.27
  GTFO, v4.51
  HandyNotes, vv1.5.9
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HealBot, v8.2.5.8
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  HealBotTips, v8.2.5.8
  Informant, v8.2.6508 (SwimmingSeadragon)
  MikScrollingBattleText, v5.7.150
  MythicPlusTimer, v3.4
  NPCScan, v8.0.1.13
  Pawn, v2.3.13
  QuickQuest, v80200.40-Release
  RaiderIO, v8.1.0 (v201912240637)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  SavedInstances, v8.2.7
  Scrap, v8.2.0
  Simulationcraft, v1.12.3
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomCats, v1.3.6
  TomCatsMechagon, v1.3.10
  TomCatsNazjatar, v1.3.10
  TomTom, vv80205-1.0.9
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WorldQuestsList, v91
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=6a6)

Error Log #4

Date: 2019-12-24 11:56:33
ID: 5
Error occured in: Global
Count: 3
Message: ..\AddOns\Bagnon_ItemLevel\main.lua line 210:
   Usage: hooksecurefunc([table,] "function", hookfunc)
Debug:
   (tail call): ?
   [C]: hooksecurefunc()
   Bagnon_ItemLevel\main.lua:210: ?()
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:20:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:18
   ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:56:
      ...ommon\Wildpants\libs\WildAddon-1.0\WildAddon-1.0.lua:53
   [C]: ?
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:29:
      ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:25
   ...ibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:64: Fire()
   ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:448: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:567: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1240:
      ..\FrameXML\UIParent.lua:1138
Locals:
None
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.25
  BagnonBoE, v1.0
  BagnonGarbage, v1.0
  BagnonItemLevel, v1.0
  BagnonScrap, v8.2.0
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  Capping, vv8.2.11
  DBMCore, v8.2.31
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyScrap, v24
  ElvUI, v11.27
  GTFO, v4.51
  HandyNotes, vv1.5.9
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HealBot, v8.2.5.8
  HealBotData, v8.2.5.0
  HealBoten, v8.2.5.0
  HealBotOptions, v8.2.5.0
  HealBotTips, v8.2.5.8
  MikScrollingBattleText, v5.7.150
  MythicPlusTimer, v3.4
  NPCScan, v8.0.1.13
  Pawn, v2.3.13
  QuickQuest, v80200.40-Release
  RaiderIO, v8.1.0 (v201912240637)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  SavedInstances, v8.2.7
  Scrap, v8.2.0
  Simulationcraft, v1.12.3
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TomCats, v1.3.6
  TomCatsMechagon, v1.3.10
  TomCatsNazjatar, v1.3.10
  TomTom, vv80205-1.0.9
  TradeSkillMaster, vv4.8.24
  TradeSkillMasterAppHelper, vv4.0.6
  WeakAuras, v2.15.5
  WorldQuestsList, v91
  BlizRuntimeLib_enUS v8.2.5.80205 <none>
  (ck=67b)

**Comment by johneballz** [comment]
I have to agree w/ gingy92 as soon as I deleted those addons the bagnon worked completely. I don't know if Jailiborc or someone else is looking possibly making those two addons or collaborating w/ the other two to fix the current issue. I love to see the Ilvl on my gear and the BOE so I know if I want to sell or scrap. thanks for the hard work you do on this addon
