### ISSUE TITLE
"That item doesn't go in that container."

### ISSUE THREAD

**Issue by Essabelle** [tullamods/Bagnon#1112]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-8.2.26-113.3 (Classic)
 - Server patch: 1.13.3.32836

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. Yes

**Describe the bug**
Class: Hunter (60). Has an ammo bag and the key chain. When clicking on the icon to clean items in the bag contents the addon is apparently trying to put items in either the ammo bag and/or the key chain. This results in the error being repeated displayed, "That item doesn't go in that container." The error keeps repeating and the only way to stop it is to do a /reload. The error appears even when the ammo bag is full. This error does NOT appear with other classes.

The last two items in the top row of the inventory are blinking rapidly. (Torch of Retribution and Dartol's Rod of Transformation).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to bag inventory
2. Click on Click to clean items icon
3. Scroll down to '....' : n/a
4. See error "That item doesn't go in that container."

**Expected behaviour**
The bags get cleaned

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the first message : Repeated error displays at top centre of screen, "That item doesn't go in that container."
![Bagnon Bag Clean-up Error](https://user-images.githubusercontent.com/58296342/71493102-ef1db000-2801-11ea-901e-88b96d0628d3.jpg)

**Additional context**

**Comment by Essabelle** [comment]
Your latest update, 8.2.27.113.3, fixed the error. Yea! But, the ammo bag didn't 'complete' as there were empty slots at the beginning and end of the bag. Minor problem, save for a dark and stormy night. 

Thanks!!   :-)

**Comment by Morons** [comment]
This is NOT fixed!!
![image](https://user-images.githubusercontent.com/22202038/134325020-5c388d46-db78-4afd-bb84-17307ada42ff.png)
It even left open spaces!!
![image](https://user-images.githubusercontent.com/22202038/134325208-f5f7a486-5069-4737-af70-20d7b736a8cb.png)

**Comment by skburgart** [comment]
Yeah, this happens for me too. Discovered it's [Light Feather] that causes it. Taking it out of my inventory resolves the issue.

**Comment by SergioT87** [comment]
Today I bought the ShaTar heroic dungeon key in TBC Classic and now the addon is trying to place items on the keychain.
This error doesn't appear on level 1 characters because they don't have a keychain.
Infinite loop. 

On the other hand the default order that the addon has by default is nefarious. This is not sorting the bag and I see that most of the players in my guild feel the same way and end up placing the items by hand.

Translated with www.DeepL.com/Translator (free version)

**Comment by chrisabruce** [comment]
Having same issues as well.

**Comment by i93sme** [comment]
This issue was resolved in a previous version of Bagnon but as of 5 days ago I have seen it resurface.
Either Light Feather, or any type of Mote will trigger the infinite loop even if it is set in order in the right bag. Once the attempt was done to put it in the keyring, the loop is infinite.

**Comment by sofar** [comment]
This begs for a "max retry" limit on sorting. I've gotten this for gray trash feather items, leather scraps and idk even what item is currently doing it.

**Comment by wabkia** [comment]
unfortunate bug to resurface considering i cant sort my bags without bagnon's auto sort :P

**Comment by i93sme** [comment]
Ok, reverting the change to FitsIn that was introduced in https://github.com/tullamods/Wildpants/commit/1d1f8d54e6123a55307cb611139d27b342d066ad seems to solve the issue.

**Comment by i93sme** [comment]
I leave it to the author to figure out why this change will set the addon to try to put things in bags where those things should not be (like erm, keyring). It might have to do with the family of the Keyring bag probably since it is a 'special' bag.
Could not find in any way a proper documentation that might lead me to understand the failure mode introduced by the change, sorry for that.

**Comment by tbonfim** [comment]
Hi guys, I'm still facing this issue today with the latest version. Steps to reproduce are the same as the original issue creator published.
