### ISSUE TITLE
Can not move item(s) to/from guild bank

### ISSUE THREAD

**Issue by jpgroulx** [tullamods/Bagnon#1125]
**Running Software: Retail Battle for Azeroth
 - Addon version: 8.2.27-8.2.5
 - Server patch: 8.2.5.32750

**Describe the bug**
I can not move items to/from the guild bank on any of toons including the guild master.
Guild gold is zero as described in another bug report

**To Reproduce**
Steps to reproduce the behaviour:
1. Open guild bank at any guild bank location.
2. Attempt to move item to/from guild bank and nothing happens.

**Expected behaviour**
Item should be moved.

**Additional context**
When disabling all add-ons except for Bagon, items still cannot be moved.
When disabling Bagon add-on, items can be moved.

**Comment by Alchymysts** [comment]
I saw three updates the past week. And after applying all of them the Guild Bank problems persist.
I am not certain if the Guild Master only can access even though I know my other non-GM characes can't.
Reloading the UI to non-Bagnon allows all to have access. So I have to assume that there is still some problem.
See jpgroulx's post for the steps, why repeat them here, they are the same with the same problem.

**Comment by jpgroulx** [comment]
I am the guild master and only when I disable the add-on can I move items.   I've also tried on multiple computers, so it's not the UI.

**Comment by Saleemo** [comment]
Also having this issue. I am an officer in the guild with all rights. I cannot reorganize, clicking on any item in the gbank simply does nothing. I am however able to move items from my bag to the gbank, but the quantity moved to the gbank is not reflected. Once I disable the addon and reload my UI I am able to see the correct quantities and use the gbank as normal.

**Comment by dbaker9752** [comment]
I am having the same issue. I have disabled the addon so that I can access my guild bank.

**Comment by irolson** [comment]
Same issue. Can add items to guild bank but not see that I have, Can not move items within guild bank.  A /reload ui fixes this but needs be done every character and every login.

**Comment by Maldric** [comment]
Can't move from/to guild bank either. Whole guild(with addon) got the same issue.

**Comment by ultima98** [comment]
Same issue. Disabling Bagnon allows items to be moved as normal, but with Bagnon enabled, no items can be moved from the guild bank. Items can be moved TO the guild bank, but they are invisible; items moved to the guild bank in this way CAN be retrieved with Bagnon enabled, but not items that were already in the guild bank. Additionally, the inventory icons and tooltips for many items in the guild bank are either incorrect or downright broken. For example, caged battle pets display with a cage icon and the tooltip simply reads "Battle Pet", rather than having the correct tooltip and icon for the specific pet; also, mousing over an item sometimes causes its tooltip to appear on ALL other guild bank items until you switch bank tabs.

**Comment by Saleemo** [comment]
Updated add on in Twitch, even restarted PC, still  having the same issues.
