### ISSUE TITLE
Bank window not opening

### ISSUE THREAD

**Issue by veljkovicm** [tullamods/Bagnon#1449]
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-10.0.3-9.2.7
 - Server patch: 10.0.0 (46313)

**Describe the bug**
Bank window not being opened. Both at the NPC or by right-clicking the addon icon.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the bank
2. Click on the NPC
3. Nothing happens, bank window is not opened

**Error Logs**
```28x ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `Layout'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:66: in function `Update'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:56: in function `RegisterSignals'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:19: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:77: in function `Toggle'
[string "@Interface/AddOns/Bagnon/addons/main/brokerPlugin.lua"]:24: in function `OnClick'
[string "@Interface/AddOns/Bagnon/addons/main/brokerCarrousel.lua"]:113: in function <...erface/AddOns/Bagnon/addons/main/brokerCarrousel.lua:110>

Locals:
(*temporary) = -1
(*temporary) = 2
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag)"
```

**Comment by thezephyrsong** [comment]
Same is happening for me

**Comment by afflock** [comment]
same for me also, broke 30 mins ago

**Comment by kinghq1** [comment]
Same.  I uncheck Bagnon under Addons and I can view my Bank.  Course this disables Bagnon . . .

**Comment by rainshdw08** [comment]
Same as kinghq1.  26 Oct 8:48am CDT.  Will have to disable for now so I can use my bank.  Would LOVE to be able to use add-on again.  :)

**Comment by jaysonbucy** [comment]
Same issue. I tried disabling just the guild bank portion and it still wouldn't open so I'm assuming it's something with the base addon.

**Comment by Teufeltrunte** [comment]
i can't open my bank either. my inventory opens but no back at all. it works if the addon is off.

**Comment by Toenail1203** [comment]
bagnon seems to work until i open my bank or try to toggle to the bank from the main bagnon 2 page LUA error. i copied this error because it looked different from the original poster.  long-time user thanking you for the work you put in.

Message: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
Time: Wed Oct 26 15:20:44 2022
Count: 1
Stack: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: ?
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `Layout'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:66: in function `Update'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:56: in function `RegisterSignals'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:19: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:47: in function <...Ons/Bagnon/common/Wildpants/features/autoDisplay.lua:46>
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals: 
Message: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
Time: Wed Oct 26 15:20:44 2022
Count: 1
Stack: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=(tail call)"]: ?
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/base.lua"]:24: in function `SendFrameSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua"]:177: in function `func'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/MutexDelay-1.0/MutexDelay-1.0.lua"]:36: in function <...mon/Wildpants/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals: <none>

**Comment by Lorienne143** [comment]
Same problem here.  I love this add-on so much and hope that someone can address it soon!

Things seem to be breaking down somewhere in here, line 188 in bag.lua:

```
if not self.cached then
		for i, atlas in ipairs(self.FILTER_ICONS) do
			local active = C_Container and (id > NUM_BAG_SLOTS and C_Container.GetBankBagSlotFlag(id - NUM_BAG_SLOTS, 2^i) or C_Container.GetBagSlotFlag(id, 2^i)) or
										 GetBagSlotFlag and (id > NUM_BAG_SLOTS and GetBankBagSlotFlag(id - NUM_BAG_SLOTS, i) or GetBagSlotFlag(id, i))
			if active then
				return self.FilterIcon.Icon:SetAtlas(atlas)
			end
		end
	end
```

I suck at coding, but my guess is that a negative value is being returned somewhere in there.

**Comment by ksaper** [comment]
Similar - seeing 3 errors, BagBrother off, Console On (Void Off, Guild Bank Off) - interacting with personal bank.

Message: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
Time: Wed Oct 26 16:37:51 2022
Count: 2
Stack: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `Layout'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:66: in function `Update'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:56: in function `RegisterSignals'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/frame.lua"]:19: in function <...ace/AddOns/Bagnon/common/Wildpants/classes/frame.lua:17>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:47: in function <...Ons/Bagnon/common/Wildpants/features/autoDisplay.lua:46>
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Message: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
Time: Wed Oct 26 16:37:51 2022
Count: 2
Stack: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function `RegisterEvents'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:73: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:18>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua"]:17: in function <.../AddOns/Bagnon/common/Wildpants/classes/bagGroup.lua:11>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:285: in function `CreateBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:265: in function `PlaceBagGroup'
[string "@Interface/AddOns/Bagnon/addons/main/frame.lua"]:91: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/base.lua"]:24: in function `SendFrameSignal'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/itemGroup.lua"]:177: in function `func'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/MutexDelay-1.0/MutexDelay-1.0.lua"]:36: in function <...mon/Wildpants/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals: <none>

Message: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
Time: Wed Oct 26 16:37:51 2022
Count: 2
Stack: ...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:188: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag))
[string "=[C]"]: in function `GetBagSlotFlag'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:188: in function `Update'
[string "@Interface/AddOns/Bagnon/common/Wildpants/classes/bag.lua"]:124: in function <...rface/AddOns/Bagnon/common/Wildpants/classes/bag.lua:123>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/frames.lua"]:85: in function `Show'
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:47: in function <...Ons/Bagnon/common/Wildpants/features/autoDisplay.lua:46>
[string "@Interface/AddOns/Bagnon/common/Wildpants/features/autoDisplay.lua"]:82: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals: (*temporary) = -1
(*temporary) = 2
(*temporary) = "outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(
