### ISSUE TITLE
Will bagnon ever be fixed???????

### ISSUE THREAD

**Issue by minimuff** [tullamods/Bagnon#1516]

**Comment by darkseid4nk** [comment]
https://github.com/AHigi   this one works.

**Comment by Markronic** [comment]
Would you be in a rush to fix things for the ungrateful people posting toxic crap as soon as the addon wasn't updated 5mins after problem occurred? I personally don't know how some mod authors put up with the trash talk they get for something they created for the community for free.

**Comment by clancyby** [comment]
Until Start 30 hours. Have you cleared your bags yet?

**Comment by sirzooro** [comment]
Addon author definitely don't care that Bagnon was downloaded from Curse over 84 millions times so far and huge number of people wait for the fix which will bring completely broken addon back to life. Sure he can go out for business or something and do not have free time to fix addons, this is fine. But he could post some information on Curse addon page or here on GitHub about current situation, this did not happen. Also for some reason he did not release any quick fix - AHigi's fix linked above changed 6 lines only, so it could be done fast. Instead of this addon author decided to work on final solution with new extra addon to support both Retail and Classic WoW API. Looks that he cares only about about people who donated, as he posted updates on Patreon only - last place where I would look for them. And even this is questionable, I doubt that donors got fixed version behind the scene.

**Comment by SisrenWarrior** [comment]
> Looks that he cares only about about people who donated

You mean to say he only cares about the people invested enough to not only support him, but are much more likely to provide meaningful help and/or critisism, rather than the masses who grabbed something for free and then proceed to complain that said free thing isn't as good as it is if you pay for it?

Imagine that.

**Comment by sirzooro** [comment]
> > Looks that he cares only about about people who donated
> 
> You mean to say he only cares about the people invested enough to not only support him, but are much more likely to provide meaningful help and/or critisism, rather than the masses who grabbed something for free and then proceed to complain that said free thing isn't as good as it is if you pay for it?
> 
> Imagine that.
> 
> EDIT: A beta fix was pushed before OP even posted.

I used to have recurring donation setup for his other addon, PetTracker. When I set it up, I asked him to document filter syntax and add small feature to addon (show in pet popups where pet comes from, info displayed in Pet Journal only by WoW itself). He updated docs quickly. However after this we started lengthy discussion about odd logical operator syntax and lack of parenthesis - I pointed out that current implementation does not resemble anything similar in programming languages, he insisted that this is ok. Eventually I gave up and cancelled my donations. After cancellation he eventually added that another feature which I asked for.

Being donor or free user does not change reality that addon author does not communicate well with his huge user base, and for some reason he did not release quick and dirty fix to "extinguish the fire" fast and deliver better fix later.

**Comment by ebmusicman84** [comment]
> Being donor or free user does not change reality that addon author does not communicate well with his huge user base, and for some reason he did not release quick and dirty fix to "extinguish the fire" fast and deliver better fix later.

Who cares?  The author is not under any obligation to anyone, they owe "the community" nothing.  Y'all are just tilting at windmills.
