### ISSUE TITLE
Bank tab not showing all slots on screen

### ISSUE THREAD

**Issue by Elohesra** [tullamods/Bagnon#367]
Since the previous update when you changed it to 12 spaces across rather than 16 it now no longer shows all spaces on screen (main bank slot, 7 x 28 slot + reagents), please revert back to how it was, ty

**Comment by Sorrowdragon** [comment]
I made a comment about this over on the curse page for this addon, I had this issue too of the bank's bag space begin defaulted to 12 columns instead of 16 columns which caused the slots to go off screen if you used a small resolution, windowed mode, or large bags. 

I found that this can be fixed manually within your Interface>addons>bagnon options, there's a bank tab option and you can change it back to 16. 

But I still think by default this should remain at 16 for users who download this addon and happen to have large bags in their bank or use smaller resolutions (older laptop users or such).
