### ISSUE TITLE
Items in cached bank not showing right stats

### ISSUE THREAD

**Issue by ssateneth** [tullamods/Bagnon#400]
If you open your bank without being at your bank (so it shows a cached version of your bank), some items with random stats dont show the random stats. I'll upload a video so you can see it when gyazo stops acting up.

**Comment by ssateneth** [comment]
http://gyazo.com/6646929106f081526d7441ca23683b30

**Comment by ssateneth** [comment]
and here is a version with the actual bank open. it shows the correct stats, but only if im talking to a bank NPC
http://gyazo.com/410b4898fc4b347ef987f138e8cc18e4

**Comment by Elesack** [comment]
Thanks for the reply, however this isnt the problem - Both Bag and Bank and Guild Bank will create the same error, the first time any are opened anywhere. Additionally, the Search function will also create an error the first time it is used. This has been happening since the game switched to V6.xxx, and has occurred in the past after updates during Pandaria. I have tried clearing everything out, and no luck. I have included the errors below.
First, just pressing B at start of game to view bag - when bag closes you get this error.
Date: 2015-07-08 09:47:25ID: 1Error occured in: GlobalCount: 1Message: ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua line 187:   attempt to index field 'FrameSettings' (a nil value)Debug:   [C]: ?   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:187: GetBagnonVariableLinks()   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:207: UpdateVisibility()   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:60: OnHide()   Bagnon\components\inventory.lua:17:      Bagnon\components\inventory.lua:16   [C]: Hide()   Bagnon\components\frame.lua:67: HideFrame()   Bagnon\components\frame.lua:322:      Bagnon\components\frame.lua:322Locals:
Next, opening the bag after this error, and clicking search button - you get this error immediately.
Date: 2015-07-08 09:48:36ID: 2Error occured in: GlobalCount: 1Message: ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua line 147:   attempt to index field 'Settings' (a nil value)Debug:   [C]: ?   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:147: BagSearch_OnUpdate()   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:51:      ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:49Locals:
Opening the Bank for the first time, still talking to the Banker, I get this error (Bag also opens for first time here) after I close the bank.
Date: 2015-07-08 09:51:40ID: 1Error occured in: GlobalCount: 1Message: ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua line 187:   attempt to index field 'FrameSettings' (a nil value)Debug:   [C]: ?   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:187: GetBagnonVariableLinks()   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:207: UpdateVisibility()   ...AddOns\Bagnon_AccountSearch\Bagnon_AccountSearch.lua:60: OnHide()   Bagnon\components\inventory.lua:17:      Bagnon\components\inventory.lua:16   [C]: Hide()   Bagnon\components\frame.lua:67: HideFrame()   Bagnon\main.lua:102: HideFrame()   Bagnon\main.lua:203: ?()   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145:      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:145   [string "safecall Dispatcher[1]"]:4:      [string "safecall Dispatcher[1]"]:4   [C]: ?   [string "safecall Dispatcher[1]"]:13: ?()   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: Fire()   Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119   [C]: CloseBankFrame()   Bagnon\components\bank.lua:12:      Bagnon\components\bank.lua:11   [C]: Hide()   Bagnon\components\frame.lua:67: HideFrame()   Bagnon\components\frame.lua:322:      Bagnon\components\frame.lua:322Locals:
Hope this helps

Date: Wed, 8 Jul 2015 09:42:02 -0700
