### ISSUE TITLE
7.2.0 opening guild bank crashes game

### ISSUE THREAD

**Issue by ceylina** [tullamods/Bagnon#530]
I had to actually take a screen shot to get this error as the game hung instantly on opening the bank. Looks to be other errors but I can't view them as it crashes before bugsack can save them

![untitled](https://cloud.githubusercontent.com/assets/9342192/24929204/cde9af44-1eca-11e7-92e5-f4d3033980b1.png)

**Comment by rruggles** [comment]
I was on the curse.com site were I reported the below, twice. Today while there I saw that we are supposed to use this Github page, so I came here and saw @ceylina's post and since it is the same error, posed my as a reply. Her's could only give a partial error report since it is a screen shot. Mine on the other hand is a full report as I was able to close the offending window before it locked up WoW.

I see that Bagnon was updated again to day and is **STILL** buggy. Below is the bug report that came from Bugsack. By the time I close the Guild bank window (just a few seconds) it reported this same error 10 times, which caused WoW to crawl. 
Please fix this error **_before releasing another version_**
 
```
10x ...aceBagnon_GuildBank\components\itemFrame.lua:12: Usage: RegisterMessage("eventname", "methodname"): 'methodname' - method 'OnShow' not found on self.
[C]: ?
...Tom\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:140: in function `RegisterMessage'
...aceBagnon_GuildBank\components\itemFrame.lua:12: in function `RegisterEvents'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:30: in function `Update'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:22: in function `New'
Bagnon\components\frame.lua:323: in function `CreateItemFrame'
Bagnon\components\frame.lua:318: in function `PlaceItemFrame'
Bagnon\components\frame.lua:84: in function `Layout'
Bagnon\components\frame.lua:59: in function `Update'
Bagnon\components\frame.lua:50: in function `RegisterMessages'
...s\Bagnon\external\Wildpants\components\frameBase.lua:18: in function <...s\Bagnon\external\Wildpants\components\frameBase.lua:16>
[C]: in function `Show'
FrameXML\UIParent.lua:2907: in function <FrameXML\UIParent.lua:2902>
[C]: in function `ShowUIPanel'
...aceBagnon\external\Wildpants\core\frames.lua:54: in function <...aceBagnon\external\Wildpants\core\frames.lua:50>
(tail call): ?
[string "BAGNON_GUILD_TOGGLE"]:2: in function <[string "BAGNON_GUILD_TOGGLE"]:1>
Locals:
(*temporary) = "Usage: RegisterMessage("eventname", "methodname"): 'methodname' - method 'OnShow' not found on self."

``` In looking back to a bug report I posted BEFORE this last release, this is **_the very same bug_**.
 
Cheers

**Comment by Jaliborc** [comment]
If you look at the changelog, you'll see the guild bank is still not ready for 7.2
If you have guildbank installed, it is because you're running an older version of Bagnon_Guild

**Comment by Jaliborc** [comment]
If you look at the changelog, you'll see the guild bank is still not ready  
for 7.2
If you have guildbank installed, it is because you're running an older  
version of Bagnon_GuildBank
