### ISSUE TITLE
After 7.2.2 update bags no longer one bag...

### ISSUE THREAD

**Issue by CaptBayou** [tullamods/Bagnon#546]
after this newest update 7.2.2 when i open my bags they are no longer one bag, did ya'll remove that feature from the addon?

**Comment by Rincenor** [comment]
Same problem as CaptBayou; tried the usual reinstall/reloads to no avail.  Saying its an out of date addon  in the addon list.  Really missing it working! Thank you

**Comment by CaptBayou** [comment]
Mine is working fine again closed client down and restarted game few hours later and it was working again, 
either it got fixed or had a driver hanging. because i also tried the uninstall an reinstall and it didn't work but it's working fine now.. .woot back in business..lol

**Comment by Rincenor** [comment]
Thanks for the info, mine did the same.....thankfully!

Sent from my iPad

On May 6, 2017, at 23:07, CaptBayou <notifications@github.com<mailto:notifications@github.com>> wrote:


Mine is working fine again closed client down and restarted game few hours later and it was working again,
either it got fixed or had a driver hanging. because i also tried the uninstall an reinstall and it didn't work but it's working fine now.. .woot back in business..lol

**Comment by Llama1337** [comment]
Got this when I first logged in after updating to 7.2.2:
```
Date: 2017-05-09 21:36:02
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Bagnon\components\optionsToggle.lua line 7:
   Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Bagnon'
Debug:
   [C]: ?
   ...AckisRecipeList\libs\AceLocale-3.0\AceLocale-3.0.lua:134: GetLocale()
   Bagnon\components\optionsToggle.lua:7: in main chunk
Locals:
(*temporary) = "Usage: GetLocale(application[, silent]): 'application' - No locales registered for 'Bagnon'"
```

Relogged, as other posters have mentioned, and all is well again.

**Comment by Jaliborc** [comment]
You updated the addon while the game was running
