### ISSUE TITLE
bank

### ISSUE THREAD

**Issue by zooloogorbonos** [tullamods/Bagnon#554]
Attempt to correct the bank's bug was unsuccessful. http://imagizer.imageshack.com/img924/9974/jfgDnZ.jpg 
http://www.wowhead.com/item=133716/soggy-drakescale
http://www.wowhead.com/item=133720/demonic-detritus

The principle of the bug is not entirely understandable, for it does not occur on all things. Specific examples gave - it's bait for a fishing rod. As written earlier - try to roll back to 4-5 versions of the addon back and understand what it was not so prescribed.

**Comment by PziCrow** [comment]
I'm having this issue as well. It seems to be caused by items put in the guild bank, which are then counted as being on all characters on the corresponding realm, even without having any of that item in the personal bag or bank.
This can lead to it showing crazy amounts. Example: I put 1000 of x ore in the guild bank and I have 10 characters on x realm = tooltip shows 1000 ore on all characters = 10.000 total.

**Comment by Jaliborc** [comment]
Duplicate
