### ISSUE TITLE
lag on item mouseover

### ISSUE THREAD

**Issue by semecan** [tullamods/Bagnon#717]
When hovering an item in my bags for the first time, I get a small lag. So when I "fly" over my inventory, the game can hang for about a second. I checked the code a bit and found it's caused by the function "AddOwners" in file "external/Wildpants/features/tooltipCounts.lua". I didn't figure out which part of it though.

**Comment by semecan** [comment]
I just rolled back to Version 7.3.2 and the addon works perfectly, without any lags. I noticed you use "LibItemCache" in the new version which may be the cause of these lags.

**Comment by Tuller** [comment]
It might be advisable to use the newer Item api:
https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/ObjectAPI/Item.lua

**Comment by Jaliborc** [comment]
C_Item might be useful to replace some GetItemInfo calls. When only the ID/name etc of the item are required.

**Comment by Jaliborc** [comment]
@semecan the tip counts need to iterate through all the characters inventories. It caches the resulting counts, so the lag won't show after the first mouse over.

**Comment by semecan** [comment]
@Jaliborc I am aware of that, but still I find it annoying to have annoying to have a one second lag when checking an item on the bottom of my bags, even if it is just the first time. Especially because when it worked perfect without any problems in version 7.3.2

**Comment by Veyska** [comment]
I can get BagBrother to spike upwards of 20-25mb and Bagnon 15+ by opening my bags and waving my mouse around over items for a couple seconds.  System's no slouch either (i7-6700, 32gb RAM, 1tb Samsung 960 EVO SSD) but said mouse flailing drops my FPS down to a third or so of its normal value until I stop.  Checked with basically zero addons enabled other than Bagnon/BagBrother (memory/CPU/fps data mod and a LDB display addon so I could check memory values) on a baby alt and it's behaving similarly (I did the mouse spam over the same inventory I tested initially, FWIW).


![hungry hungry bagbrother](https://user-images.githubusercontent.com/2243477/43243749-99a66246-9097-11e8-9c9e-1aa2641d5a38.jpg)
(First column is current memory, second is increase since last status update, which is every second or so that the tooltip is displayed I think.)

**Comment by semecan** [comment]
Is it possible, to disable the caching of items for testing?

**Comment by Gatheringofravens** [comment]
This seems to happen even after having moused over items for the first time, at least upon restarting the game. I also am getting actual freezing whenever I mouse over item rewards in my WOD Garrison planner table. I do have the master plan addon but this doesn't appear to be an issue with it. With the bags issue the game just stutters a little bit. In this case it often takes several seconds for the tooltip to appear. Bagnon is also using a fair amount of memory. I can't honestly recall if 18 MB is about normal for it or not, just can't remember seeing it in my top three often before. Not an issue at all by itself given how much memory modern computers have but might as well mention the fact. Needless to say it can use 100 MB and I don't mind a bit, it's the stuttering issues that are the problem.

**Comment by Jaliborc** [comment]
@semecan @Gatheringofravens @Veyska let me know if the issue persists when the new release comes out. Reduced memory usage of tooltip counts by about 80%.

**Comment by semecan** [comment]
A very tiny lag still exists, but it is bearable.
Thank you!
