### ISSUE TITLE
Total gold not showing in bag

### ISSUE THREAD

**Issue by Izibb** [tullamods/Bagnon#751]
Since BfA updates, total gold for all characters is not displaying correctly anymore, see screenshot : 

<img width="209" alt="screen shot 2018-08-09 at 16 25 36" src="https://user-images.githubusercontent.com/42244443/43905276-08f8eccc-9bf1-11e8-8b45-6a98ceae9097.png">

**Comment by Ekhiel** [comment]
I have the exact same problem.

**Comment by Krakken77** [comment]
I also have this problem. And I cannot see my other toons within the realm where this problem occur.
But this occur only on one realm "La Confrérie du Thorium" for me. Maybe because it's a linked realm or because of the extra char "é" in the name of this realm.
On the other side, for another realm "Kirin Tor" the total of gold is showing and I can see all my other toons within this realm.

**Comment by Yazoolol** [comment]
Same problem here.
I'm not in a realm or have toons with special characters

**Comment by Krakken77** [comment]
I have seen another thread which seems to be discussing about the same problem:
Item count tooltip broken #726
But as on the 3rd of september, the latest patch of bagnon has still not correct this problem.

**Comment by Joccob** [comment]
Same problem here. I play on Sargeras-US.
