### ISSUE TITLE
Not holding column settings per character

### ISSUE THREAD

**Issue by Nexus-V** [tullamods/Bagnon#758]
Every character I log onto I have to reset the column count on the inventory, bank, and void storage. I just logged out after fixing one character's bags and when I go to log in again, I will have to fix them again.
I am using Bagnon 8.0.2.

**Comment by Manarri** [comment]
This has been driving me nuts as well. There are two issues to this that I'm running into: first, that the addon isn't saving any settings across updates, which is bizarre for an addon that has done that for years; and second, that any settings made are account wide, and not character specific, which is just obnoxious. 

I only bother with a main toon, and a bank alt, but these characters do not have the same number of bag slots, and it doesn't make sense for them to be stuck with the same number of collums. I can't imagine the frustration of someone who actually plays alts. For the first time since getting Bagnon, I'm starting to look at other bag addon options.

**Comment by Jaliborc** [comment]
I believe the latest version fixed the issue. Let me know if it did not
