### ISSUE TITLE
Bagnon still not working at all

### ISSUE THREAD

**Issue by Pestfr0sch** [tullamods/Bagnon#947]
So, I've just read through a hole bunch of  Issues to find a solution for my problem but none of them was working.

My Bagnon won't open my bags at all. No new keybinding helps, no changes in my options, nothing. And this is going on since like forever (no, honestly it started during Legion and I have no idea why).

I'm so mad at this situtation that today I disabled all my AddOns and only activated Bagnon. And still - I hear the sound of opening bags but I can't see anything. At this point - knowing there's no conflict with other AddOns - I'm pretty much out of ideas and would be really happy if anyone knows what the hell is going on :D

**Comment by 0utlierrr** [comment]
You need to go to the twitch app, click bagnon, click versions, and select the previous version. This will fix it until the dev updates.

**Comment by Pestfr0sch** [comment]
Worth a shot. But as I mentioned, I have this problem since Legion. It didn't appear after the release of the newest patch. Even when trying every version since the release of BfA my bags wouldn't be shown.

But just for sh*t and giggles I tried the previous version. With the exact same problem.

:/

**Comment by Shiroma51** [comment]
Then I suggest you find a version prior to legion and try that. :).  All i want is 1 bag not 5 and that should work.

**Comment by vern1701** [comment]
Date: 2019-07-04 14:23:47
ID: 4
Error occured in: Global
Count: 1
Message: ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua line 245:
   C stack overflow
Debug:
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...
   ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:245:
      ...uidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:27:
      ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:25
   ...Wildpants\libs\LibItemCache-2.0\LibItemCache-2.0.lua:111: owners()
   ...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:35:
      ...ace\AddOns\Bagnon\external\Wildpants\core\owners.lua:33
   (tail call): ?
   Bagnon\components\frame.lua:126: ListMenuButtons()
   Bagnon\components\frame.lua:110: PlaceMenuButtons()
   Bagnon\components\frame.lua:75: Layout()
   Bagnon\components\frame.lua:60: Update()
   Bagnon\components\frame.lua:50: RegisterSignals()
   ...s\Bagnon\external\Wildpants\components\frameBase.lua:18: OnShow()
   ...s\Bagnon\external\Wildpants\components\inventory.lua:16:
      ...s\Bagnon\external\Wildpants\components\inventory.lua:15
   [C]: Show()
   ...ace\AddOns\Bagnon\external\Wildpants\core\frames.lua:55: ShowFrame()
   ...s\Bagnon\external\Wildpants\features\autoDisplay.lua:70: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
self = <table> {
 GetLibraryVersion = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:585
 argCheck = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:129
 error = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:75
 pcall = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:167
}
key = "IsItemCache"
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:237
(*temporary) = <table> {
 GetLibraryVersion = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:585
 argCheck = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:129
 error = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:75
 pcall = <function> defined @Interface\AddOns\SharedMediaLib\libs\AceLibrary\AceLibrary.lua:167
}
(*temporary) = "IsItemCache"
(*temporary) = "C stack overflow"
lib = <table> {
 GetLine = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:184
 GetText = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:162
 SetHyperlink = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetShapeshift = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 FindDeformat = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:134
 SetPlayerBuff = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetCraftItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetQuestRewardSpell = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 MultiFind = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:120
 SetPetAction = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetUnitDebuff = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 CreateSetMethods = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:214
 NumLines = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:73
 Erase = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:57
 SetInboxItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetBuybackItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetGuildBankItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetUnitBuff = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetMerchantItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetQuestLogItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetSpell = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetTradeTargetItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetTalent = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 SetCraftSpell = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:218
 CreateTooltip = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGratuity-3.0.lua:26
 SetSendMailItem = <function> defined @Interface\AddOns\ZygorGuidesViewer\Libs\LibGratuity-3.0\LibGrat
AddOns:
  Swatter, v8.2.6241 (SwimmingSeadragon)
  Ace3, v
  AceGUI30SharedMediaWidgets, v
  ACP, vr259 
  AtlasLoot, vv8.10.00
  AucAdvanced, v8.2.6295 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6231 (SwimmingSeadragon)
  AucStatSimple, v8.2.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6235 (SwimmingSeadragon)
  AutoRepair, v
  Bagnon, v8.2.0
  Bartender4, v4.8.3
  BeanCounter, v8.2.6293 (SwimmingSeadragon)
  BrokerEverything, v3.6.6-release
  CallbackHandler10, v
  Carbonite, vv8.2.0
  CarboniteQuests, vv8.2.0
  Chatter, v1.5.8
  ChocolateBar, vv3.2.3
  DejaCharacterStats, v800r122
  ElkBuffBars, v2.5.2-193
  FBTrackingFrame, v1.10
  FishingBuddy, v1.10
  Grail, v099
  GrailQuestsenUS, v27178
  HereBeDragons, v2.01-release
  HereBeDragons10, v2.01-release
  Immersion, v1.1.0
  KillTrack, vv2.12.4
  LibBabbleBoss30, v
  LibBabbleFaction30, v
  LibBabbleInventory30, v
  LibBabbleItemSet30, v
  LibBabbleSubZone30, v
  LibDualSpec10, vv1.13
  LibGraph20, v2.0.4
  LibMapData10, v1.0.r148
  LibPeriodicTable31, vv3.3.0.610
  LibQTip10, v8.0.1.1
  LibRealmInfo, v14
  LibSharedMedia30, v3.0-110
  LibStub, v
  MikScrollingBattleText, v5.7.149
  Overachiever, v1.0.5
  Pawn, v2.2.43
  Postal, vv3.6.0
  Prat30, vr1195      
  Prat30Libraries, v
  QuestCompletist, v109.23
  Recount, vv8.2.0a
  SharedMedia, v3.1.0-191
  SharedMediaAdditionalFonts, v1.0.26
  SharedMediaLib, v1.0
  Skillet, v4.08
  SlideBar, v8.2.6273 (SwimmingSeadragon)
  Stubby, v8.2.6274 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20190702
  WoWDBProfiler, v
  WoWGatheringNodes, vBFA-8.2-update-v1.0
  XLoot, v8.1-1
  XLootFrame, v8.1-1
  XLootGroup, v8.1-1
  XLootMaster, v8.1-1
  XLootMonitor, v8.1-1
  XPBarNone, v80000-2
  ZPerl, v5.7.7
  ZPerlArcaneBar, v
  ZPerlPlayer, v
  ZPerlTarget, v
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=7f3)

This is the full error code.  It looks like a LibGratuity error in another addon, but since Bagnon is affected in the frame.lua area I posted it here.

**Comment by vern1701** [comment]
Stack overflows are the worst bugs.

**Comment by Jaliborc** [comment]
The error you posted is not from Bagnon
